Faca um programa que leia dois vetores de 10 elementos. Crie um vetor que seja a uniao entre os 2 vetores anteriores, ou seja, que contem os numeros dos dois vetores. Nao deve conter numeros repetidos. 

In [1]:
import numpy as np

In [2]:
a = np.random.randint(low=20, size=10)
b = np.random.randint(low=20, size=10)

print(a)
print(b)

c = set(a)|set(b)
c = np.array(list(c))

print(c)

[ 3 11  0  2  6 15 11  4 10 10]
[11  0 17  0 16 19 11  3  9  9]
[ 0  2  3  4  6  9 10 11 15 16 17 19]
