Faca um programa que leia dois numeros a e b (positivos menores que 10000) e:

- Crie um vetor onde cada posicao e um algarismo do numero. A primeira posicao e o algarismo menos significativo;
- Crie um vetor que seja a soma de a e b, mas faca-o usando apenas os vetores construıdos anteriormente.

Dica: some as posicoes correspondentes. Se a soma ultrapassar 10, subtraia 10 do
resultado e some 1 a proxima posicao.

In [1]:
import numpy as np
import random as rd

In [33]:
x = np.array(list(str(rd.randint(0,10000)).zfill(4)), dtype=int)
y = np.array(list(str(rd.randint(0,10000)).zfill(4)), dtype=int)
print(x)
print(y,'\n')

x = np.insert(x, [1], x[-1])  if x[0] == 0 else np.insert(x, [0], x[-1])
y = np.insert(y, [1], y[-1])  if y[0] == 0 else np.insert(y, [0], y[-1])
print(x)
print(y,'\n')

x = np.delete(x, [-1])
y = np.delete(y, [-1])
print(x)
print(y,'\n')

soma = x+y
print(f'Vetor soma: {soma}')

[8 2 5 1]
[0 5 4 2] 

[1 8 2 5 1]
[0 2 5 4 2] 

[1 8 2 5]
[0 2 5 4] 

Vetor soma: [ 1 10  7  9]
