# O que e o numpy?

A API Numpy, abreviatura de (numeric python) é usada extensivamente em Pandas, SciPy, Matplotlib, scikit-learn, scikit-image e na maioria dos outros pacotes de ciência de dados e Python científicos.</br></br>

Muito utilizado para arrays/matrizes de n dimensoes, com operaçoes aritméticas rapidas sem uso de laços. Numpay é o pacote fundamental para computacao cientifica em python, um lib que fornece o obejeto ndarray, uma matriz de n dimensoes, que contém dados de tipos homogeneos. Varios objetos derivados e uma variedade de funcoes/rotina para operacoes rapidas com arrays, incluindo:

- Matematica logica
- Manipulacao do shape da matriz
- Classificaçao
- Seleçao
- Algebra linear basica
- Operaçoes artimeticas
- Operaçoes estatisticas basica
- Simulaçao aleatoria e muito mais</br></br>


Com muitas operaçoes sendo executadas em codigo compilado, ou seja, um codigo que foi transformado em linguagem de maquina para mais desempenho.<br><br>

Referemcia: https://numpy.org/doc/stable/user/whatisnumpy.html#what-is-numpy

# Trasmissao/Vetorizacao, o motivo de o numpy ser rapido

<>>> Estudo profundo <<<>
</br> 
</br> Referebcia: https://numpy.org/doc/stable/user/basics.broadcasting.html#broadcasting

# Qual é a diferença entre uma lista Python e uma matriz NumPy?

Para criar matrizes com o numpy nao é necessario usar loops, listas e condiçoes, por isso o numpy é de 10 a 100x mais rapido que as arrays/listas do python<br><br>

Devido a lib numpy ter sido densenvolvida em C, ela é mais eficiente que a array/lista do python, pois a linguagem C é mais baixo nivel que o python, o que facilita e agiliza o processamento dos programas<br><br>

As arrays numpy tem tamanho fixo na criaçao, ao contrario da array/lista do python que podem crescer. Ao adicionar um elemento dentro de um array numpy, esse array sera excluido e um array novo sera gerado contendo o numero que foi adicionado<br><br>

Todos os elementos de uma matriz numpy devem ser do mesmo tipo e tamanho de dado<br><br>

As arrays numpy facilitam operaçoes matematicas avançadas com uma grande quantidade de dados, ja a array/lista do python fica para tras com sua baixa eficiencia<br><br>

referencia: https://numpy.org/doc/stable/user/whatisnumpy.html#why-is-numpy-fast

# O que é uma matriz numpy?

A matriz do numpy é a ndarray, uma classe que possui vários métodos e atributos que retorna um tipo de matriz.<br><br>

Ndarray  é a abreviação de “matriz N-dimensional”. Uma matriz N-dimensional é simplesmente uma matriz com qualquer número de dimensões, essas matrizes sao containers rapidos e flexiveis para trabalhar com grandes conjuntos de dados.<br><br>

Tipo de arrays/matrizes: ndarrays >> Sigifica arrays de N dimensoes
1-D array >> Possui apenas 1 dimensao, sera chamado de vetor
2-D array >> Possui 2 dimensoes, sera chamado de matriz
3-D array >> Possui 3 ou mais dimensoes, sera chamado de tensor<br><br>

Algumas caracteristicas de uma matriz/ndarray numpy:
- permite realizar operaçoes matematicas em blocos inteiros
- Possui uma grade de elementos que podem ser indexados de varias maneiras
- Os elementos sao todos do mesmo tipo
- A ordem/shape da matriz é uma tupla com numeros inteiros maiores que 0, que fornece o tamanho da matriz em cada dimensao
- Uma maneira de criar uma matriz usando elementos do python é aninhando listas
- Acessar um elemento ou mais de uma matriz numpy é parecido com a maneira que se acessa elemtos de uma lista python<br><br>

Geralmente as dimensoes de uma matriz sao chamdas de eixo, por exemplo uma matriz 3x3 tem tem 2 eixos e cada eixo tem 3 vetores.<br><br>

Assim como obejetos do python uma matriz numpy pode ser acessada e modificada indexando ou fatiando um array. Arrays que sao copiados de forma rasa compartilharao auteraçoes.<br><br>

Mais sobre atributos de array: https://numpy.org/doc/stable/reference/arrays.ndarray.html#arrays-ndarray

Mais sobre objetos de array: https://numpy.org/doc/stable/reference/arrays.html#arrays

In [2]:
import numpy as np

In [13]:
# Array 1-D ou vetor
matriz = np.array(range(10))
print(matriz)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
# Array 2-D ou Matriz
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
# Array 3-D ou tensor
matriz = np.array([[[1,2,3],[4,5,6],[7,8,9]], [[1,2,3],[4,5,6],[7,8,9]]])
print(matriz)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


# Como criar um array básico 

https://numpy.org/doc/stable/user/absolute_beginners.html#how-to-create-a-basic-array<br><br>

- np.array() 
- np.zeros() 
- np.ones()
- np.full()
- np.empty()
- np.arange()
- np.linspace()
- dtype

## np.array()
https://numpy.org/doc/stable/reference/generated/numpy.array.html?highlight=numpy%20array#numpy-array

Funcionalidade: 
- Transforma uma iterable em uma ndarray, uma matriz de n dimensoes<br><br>

Parametros:
- ( object ) Uma iterable com caracteristicas de uma lista python, pode ser aninhada ou nao,  se estiver aninhada todas as iterables deverao ter o mesma quantidade de elementos
- ( dtype = None ) Tamanho e tipo de dado dos elementos da matriz
- ( copy = True ) Faz uma copia de um array de forma profunda, por padrao vem True 
- ( ndmin = 0 ) Numero de dimensoes da matriz
- ( * ) 
- ( order = 'K' ) 
- ( subok = False ) 
- ( like = None ) 

In [16]:
matriz = np.array(object=[1,2,3,4,5,6], dtype='int64', ndmin=2, copy=False)

print(matriz,'\n')
print(matriz.dtype)
print(matriz.ndim)
print(matriz.shape)

[[1 2 3 4 5 6]] 

int64
2
(1, 6)


## np.zeros()

https://numpy.org/doc/stable/reference/generated/numpy.zeros.html

Funcionalidade:
- Cria uma ndarray, com todos os elementos igual a zero<br><br>

Parametros:
- ( shape ) Ordem da matriz
- ( dtype = float ) Tamanho e tipo de dado dos elementos da matriz
- ( order = 'C' ) 
- ( * )
- ( like = None )

In [17]:
matriz = np.zeros(shape=(1,4), dtype='float64')
print(matriz)

[[0. 0. 0. 0.]]


## np.ones()
https://numpy.org/doc/stable/reference/generated/numpy.ones.html

Funcionalidade:
- Cria uma ndarray, com todos os elementos igual a 1<br><br>

Parametros:
- ( shape ) Ordem da matriz
- ( dtype = float ) Tamanho e tipo de dado dos elementos da matriz
- ( order = 'C' ) 
- ( * )
- ( like = None )

In [18]:
matriz = np.ones(shape=(4,4), dtype='float64')
print(matriz)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## np.full()
https://numpy.org/doc/stable/reference/generated/numpy.full.html?highlight=full#numpy.full

Funcionalidade:
- Cria uma ndarray, com todos os elementos igual ao fill_value<br><br>

Parametros:
- ( shape ) Ordem da matriz
- ( fill_value ) Valor especificado para a criaçao da matriz
- ( dtype = float ) Tamanho e tipo de dado dos elementos da matriz
- ( order = 'C' ) 
- ( * )
- ( like = None )

In [24]:
matriz = np.full(shape=(3,3), fill_value=9, dtype=float)
print(matriz)

[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]


## np.empty()
https://numpy.org/doc/stable/reference/generated/numpy.empty.html

Funcionalidade:
- Cria uma ndarray com que contem elementos aleatorios com base no dtype que for escolhido<br><br>

Parametros:
- ( shape ) Ordem da matriz
- ( dtype = float ) Tamanho e tipo de dado dos elementos da matriz
- ( order = 'C' ) 
- ( * )
- ( like = None )

In [20]:
matriz = np.empty(shape=(3,3), dtype='float16')
print(matriz)

[[-5.4453e+00 -1.1993e-01  8.9938e+01]
 [ 0.0000e+00  0.0000e+00  0.0000e+00]
 [ 0.0000e+00  0.0000e+00  3.8147e-06]]


## np.arange()
https://numpy.org/doc/stable/reference/generated/numpy.arange.html

Funcionalidade:
- Cria uma ndarray com elementos determinados pelo intervalo que comeca no start e acaba no stop, e possivel usar o step para poder escolher uma ordem crescente, decrescente ou pulando<br><br>

Parametros:
- ( start ) Inicio do intervalo
- ( stop ) Fim do intervalo
- ( step ) Numeros inteiros ou reais, negativos ou positivos
- ( dtype=Nenhum ) Tamanho e tipo de dado dos elementos da matriz
- ( * ) 
- ( like=Nenhum )

In [21]:
matriz = np.arange(start=10, stop=40, step=1.5, dtype=float)
print(matriz)

[10.  11.5 13.  14.5 16.  17.5 19.  20.5 22.  23.5 25.  26.5 28.  29.5
 31.  32.5 34.  35.5 37.  38.5]


## np.linspace()
https://numpy.org/doc/stable/reference/generated/numpy.linspace.html

Funcionalidade:
- Cria uma ndarray com base no incio, fim, e quantos numeros sao pedidos
- Eé como se criasce uma PA, aonde o inicio é o 1 termo, o fim é o ultimo termo, e quantidade de numeros é a quantidade de termos
- As vezes o retorno é uma matriz com elementos numericos do tipo float que contém dizimas periodicas, as vezes numeros float sem periodos<br><br>

Parametros:
- ( start ) Inicio do intervalo
- ( stop ) Fim do intervalo
- ( num = 50 ) Quantidade de numeros pedidos, por padrao é 50
- ( endpoint = True ) Serve para incluir o stop como elemento
- ( retstep = False ) Serve para mostrar ao usuario a razao que foi usada
- ( dtype = None ) Tamanho e tipo de dado dos elementos da matriz
- ( axis = 0 ) Serve para defirnir como os elementos da array vao ser organizados, se no start ou stop for usado um array 1-D, o axis/eixo pode ser mudado para 1 ou continuar em 0, se for 2-D o axis/eixo pode ser mudado para 2 e assim por diante. 

In [22]:
# Axis igual a 1
matriz = np.linspace(start=[1,1], stop=10, num=10, endpoint=True, retstep=False, dtype=None, axis=1)
print(matriz,'\n')

# Axis igual a 0
matriz = np.linspace(start=[1,1], stop=10, num=10, endpoint=True, retstep=False, dtype=None, axis=0)
print(matriz)

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]] 

[[ 1.  1.]
 [ 2.  2.]
 [ 3.  3.]
 [ 4.  4.]
 [ 5.  5.]
 [ 6.  6.]
 [ 7.  7.]
 [ 8.  8.]
 [ 9.  9.]
 [10. 10.]]


# 2 formas de criar um array com valores aleatorios<br>

- np.random.rand()<br>
- np.random.randint()

## np.random.rand()
https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html?highlight=rand#numpy.random.rand

Funcionalidade:
- Cria uma ndarray com elementos entre 0 e 1 <br><br>

Parametros:
- Recebe um numero para uma matriz de 1 dimensao
- Recebe 2 numero para uma matriz de 2 dimensao
- recebe n numeors para uma matriz de n dimensoes

In [29]:
matriz = np.random.rand(3,3,4)
print(matriz)

[[[0.98323907 0.61217996 0.71456293 0.50452752]
  [0.57497992 0.38103962 0.18462111 0.40215592]
  [0.72956675 0.41738063 0.53147817 0.46647465]]

 [[0.5836447  0.00873876 0.37157705 0.6008349 ]
  [0.58387205 0.71194777 0.76665957 0.56771301]
  [0.41218785 0.44486352 0.79646019 0.44783519]]

 [[0.61859627 0.1022327  0.40476015 0.3458706 ]
  [0.59991756 0.81693469 0.60734166 0.27827352]
  [0.95125441 0.06526358 0.66237774 0.43723773]]]


## np.random.randint()

https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html?highlight=randint#numpy-random-randint

Funcionalidade:
- Cria uma ndarray com a quantidade de elementos igual a size entre o intervalo criado espebelecido pelo low e o high <br><br>

Parametros:
- ( low ) Onde começa o intervalo
- ( high=None ) Onde acaba o intervalo
- ( size=None ) Ordem ou comprimento da matriz, depende da dimensao
- ( dtype=int ) Tamanho e tipo de dado

In [35]:
matriz = np.random.randint(low=1, high=100, size=(3,3), dtype=int)
print(matriz)

[[55 21 31]
 [46 66 49]
 [81 53 22]]


# Adicionando, removendo e classificando elementos 

https://numpy.org/doc/stable/user/absolute_beginners.html#adding-removing-and-sorting-elements<br><br>

- np.sort()
- np.argsort()
- np.lexsort()
- np.searchsorted()
- np.partition()
- np.concatenate()

## np.sort()
https://numpy.org/doc/stable/reference/generated/numpy.sort.html#numpy-sort

Funcionalidade:

     >> Ordena um array n-dimensional de qualquer tipo de dado. A funçao ordena o array de forma ascendente por padrao.
<br>
Parametros:<br>

- ( a )
       >> Estrutura array. Array que sera ordenado 

- ( axis = -1 ) 
       >> Um numero inteiro. Representa o eixo ao longo do qual a funçao ira ordenar a matriz, o seu valor padrao é -1, o que significa que a funçao ordenara a matriz ao longo do seu ultimo eixo.
       
       >> Ser o axis for igual a >None<, a funçao convertera o array de n_dimensoes em unidimencional antes da ordenaçao, devolvendo assim um array unidimencional
       
       >> Uma matriz 3x4 tem 2 dimensoes, logo um shape = (3, 4)
       
       axis = 0 siginifica shape[1]
       axis = 1 significa shape[0]
       
       >> E como se fosse a ordem de indexaçao do python, so que ao contrario. Aonde o começo é o primeiro eixo, no caso as colunas.
       
- ( kind='quicksort' )
       >> E uma string. Representa o nome do algoritmo de ordenaçao. Os algoritmos de ordenaçao aceitos pelafunçao sao: 'quicksort', 'mergesort', 'heapsort' e 'stable' 

- ( order=None )
       >> Pode ser uma string ou uma lista de string. Quando os campos de um array sao definidos, este parametro é ultilizado para especificar o campo a comparar primeiro.

In [77]:
# Parametro axis
matriz = np.array([[5, 2, 3], [7, 4, 1], [8, 6, 9]])
print(matriz,'\n')

# Axis igual a None
matriz_n1 = np.sort(a=matriz.copy(), axis=None, kind='quicksort', order=None)
print(matriz_n1,'\n')

# Axis igual a 0
matriz_n2 = np.sort(a=matriz, axis=0, kind='quicksort', order=None)
print(matriz_n2,'\n')

# Axis igual a 1
matriz_n3 = np.sort(a=matriz, axis=1, kind='quicksort', order=None)
print(matriz_n3,'\n')

# Axis igual a -1
matriz_n4 = np.sort(a=matriz, axis=-1, kind='quicksort', order=None)
print(matriz_n4)

[[5 2 3]
 [7 4 1]
 [8 6 9]] 

[1 2 3 4 5 6 7 8 9] 

[[5 2 1]
 [7 4 3]
 [8 6 9]] 

[[2 3 5]
 [1 4 7]
 [6 8 9]] 

[[2 3 5]
 [1 4 7]
 [6 8 9]]


In [73]:
# Parametro order
tipo = np.dtype([('nome','S10'), ('idade', int), ('altura', float)])
matriz = np.array(
    [('huan', 17, 1.80), 
    ('luigi', 19, 1.77), 
    ('lucas', 18, 1.82), 
    ('adroir', 44, 1.75)], dtype=tipo)

# Ordenando por nome
matriz_n1 = np.sort(a=matriz, kind='quicksort', order='nome')
print(matriz_n1,'\n')

# Ordenando por idade
matriz_n1 = np.sort(a=matriz, kind='quicksort', order='idade')
print(matriz_n1,'\n')

# Ordenando por idade
matriz_n1 = np.sort(a=matriz, kind='quicksort', order='altura')
print(matriz_n1)

[(b'adroir', 44, 1.75) (b'huan', 17, 1.8 ) (b'lucas', 18, 1.82)
 (b'luigi', 19, 1.77)] 

[(b'huan', 17, 1.8 ) (b'lucas', 18, 1.82) (b'luigi', 19, 1.77)
 (b'adroir', 44, 1.75)] 

[(b'adroir', 44, 1.75) (b'luigi', 19, 1.77) (b'huan', 17, 1.8 )
 (b'lucas', 18, 1.82)]


## np.argsort()
https://numpy.org/doc/stable/reference/generated/numpy.argsort.html#numpy-argsort