Faca um programa que receba do usuario dois vetores, A e B, com 10 numeros inteiros cada. Crie um novo vetor denominado C calculando C = A - B. Mostre na tela os dados do vetor C.

In [1]:
import numpy as np

In [14]:
a = np.array(np.random.randint(low=100, size=10), dtype=int)
b = np.array(np.random.randint(low=100, size=10), dtype=int)

c = a-b

print(a)
print(b)
print(c)

[67  9 63 85 33 64 80  5 98 23]
[ 7 61 27 34 33  8 21 77 20 18]
[ 60 -52  36  51   0  56  59 -72  78   5]
