Leia dois vetores de inteiros x e y, cada um com 5 elementos (assuma que o usuario nao
informa elementos repetidos). Calcule e mostre os vetores resultantes em cada caso
abaixo:

- Soma entre x e y: soma de cada elemento de x com o elemento da mesma posic¸ao˜
em y.
- Produto entre x e y: multiplicac¸ao de cada elemento de ˜ x com o elemento da mesma
posic¸ao em ˜ y.
- Diferenc¸a entre x e y: todos os elementos de x que nao existam em ˜ y.
- Intersec¸ao entre ˜ x e y: apenas os elementos que aparecem nos dois vetores.
- Uniao entre ˜ x e y: todos os elementos de x, e todos os elementos de y que nao˜
estao em ˜ x.

In [5]:
import numpy as np
import random as rd

In [15]:
a = np.array(rd.sample(range(10), 5))
b = np.array(rd.sample(range(10), 5))

print(a)
print(b)

[0 8 5 2 4]
[0 7 6 9 5]


In [32]:
soma = a+b
print(soma)

[ 0 15 11 11  9]


In [31]:
produto = a*b
print(produto)

[ 0 56 30 18 20]


In [30]:
x = set(a)-set(b)
x = np.array(list(x))
print(x)

[8 2 4]


In [29]:
y = set(a) & set(b)
y = np.array(list(y))
print(y)

[0 5]


In [28]:
z = set(a) | set(b)
z = np.array(list(z))
print(z)

[0 2 4 5 6 7 8 9]
